### ISSUE TITLE
the arxiv paper link is for nips 20 workshop

### ISSUE THREAD

**Issue by lipingcoding** [fedelopez77/sympa#1]
the arxiv paper link is for nips 20 workshop

**Comment by fedelopez77** [comment]
Code for the papers "Symmetric Spaces for Graph Embeddings: A Finsler-Riemannian Approach" (link to paper coming soon) published at ICML 2021, and the paper "Hermitian Symmetric Spaces for Graph Embeddings" published at DiffGeo4DL @ NeurIPS 2020.
