### ISSUE TITLE
How to draw Figure 1?

### ISSUE THREAD

**Issue by xiaoiker** [fedelopez77/sympa#2]
Hey, thanks very much for this great work and especially for the released code for this study. I am trying to figure out what make it a better choice to pure hyperbolic model. But first a quick question. How did you draw the Figure 1 in the ICML paper? It looks great.

**Comment by fedelopez77** [comment]
Hi, 
the drawing are the work of [Steve Trettel](http://www.stevejtrettel.site/). You can reach out to him for a detailed explanation.
Best,
Fede
